### ISSUE TITLE
XML errors

### ISSUE THREAD

**Issue by ingbrzy** [ygorigor/Romanian_MIUI7#75]
Fix errors please

http://translators.xiaomi.eu/XML_MIUI7-Romanian-ro.html

**Comment by ygorigor** [comment]
I did some changes to this files but after I saw this errors and I removed all commits and reverted all changes I made. So I don't know why this errors are not removed from http://translators.xiaomi.eu/XML_MIUI7-Romanian-ro.html

**Comment by ingbrzy** [comment]
see my corrections in you repo.. follow it for others...

**Comment by ygorigor** [comment]
If you look in the english xmls the " &lt; &gt; font " are present so I can't understand why they give errors

**Comment by ingbrzy** [comment]
just remove them... its causing parse errors...

**Comment by ygorigor** [comment]
I modified and checked all files with xml tools in notepad++. it shows no more errors
